name: AI Pipeline Update

on:
  push:
    branches: [ main ]

jobs:
  ai_update:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Установить Node.js
        uses: actions/setup-node@v3
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          node-version: 24

      - name: Установить зависимости
        run: npm install dotenv @octokit/rest node-fetch@3

      - name: Запустить AI Runner
        run: node ai_runner.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}